### ISSUE TITLE
Detail the architecture for the execute component and actuators

### ISSUE THREAD

**Issue by nmsa** [eubr-atmosphere/tma-framework-e#1]
Define the architecture for the solution.

**Comment by joseadp** [comment]
@nmsa for this issue, I worked on two repositories:
* Knowledge Component/branch: https://github.com/eubr-atmosphere/tma-framework-k/tree/actuator-definition
* Execute Component/branch: https://github.com/eubr-atmosphere/tma-framework-e/tree/jose-update-architecture

Let me know what other changes/definitions are needed.
